/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class AAscendingAscendingOrDescending extends PAscendingOrDescending
{
    private TAscending _ascending_;

    public AAscendingAscendingOrDescending()
    {
    }

    public AAscendingAscendingOrDescending(
        TAscending _ascending_)
    {
        setAscending(_ascending_);

    }
    public Object clone()
    {
        return new AAscendingAscendingOrDescending(
            (TAscending) cloneNode(_ascending_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAscendingAscendingOrDescending(this);
    }

    public TAscending getAscending()
    {
        return _ascending_;
    }

    public void setAscending(TAscending node)
    {
        if(_ascending_ != null)
        {
            _ascending_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _ascending_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_ascending_);
    }

    void removeChild(Node child)
    {
        if(_ascending_ == child)
        {
            _ascending_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_ascending_ == oldChild)
        {
            setAscending((TAscending) newChild);
            return;
        }

    }
}
