/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class ABlankWhenZeroClauseClause extends PClause
{
    private PBlankWhenZeroClause _blankWhenZeroClause_;

    public ABlankWhenZeroClauseClause()
    {
    }

    public ABlankWhenZeroClauseClause(
        PBlankWhenZeroClause _blankWhenZeroClause_)
    {
        setBlankWhenZeroClause(_blankWhenZeroClause_);

    }
    public Object clone()
    {
        return new ABlankWhenZeroClauseClause(
            (PBlankWhenZeroClause) cloneNode(_blankWhenZeroClause_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlankWhenZeroClauseClause(this);
    }

    public PBlankWhenZeroClause getBlankWhenZeroClause()
    {
        return _blankWhenZeroClause_;
    }

    public void setBlankWhenZeroClause(PBlankWhenZeroClause node)
    {
        if(_blankWhenZeroClause_ != null)
        {
            _blankWhenZeroClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _blankWhenZeroClause_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_blankWhenZeroClause_);
    }

    void removeChild(Node child)
    {
        if(_blankWhenZeroClause_ == child)
        {
            _blankWhenZeroClause_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_blankWhenZeroClause_ == oldChild)
        {
            setBlankWhenZeroClause((PBlankWhenZeroClause) newChild);
            return;
        }

    }
}
