/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class ADateFormatClause extends PDateFormatClause
{
    private TDate _date_;
    private TFormat _format_;
    private TIs _is_;
    private TDataName _dataName_;

    public ADateFormatClause()
    {
    }

    public ADateFormatClause(
        TDate _date_,
        TFormat _format_,
        TIs _is_,
        TDataName _dataName_)
    {
        setDate(_date_);

        setFormat(_format_);

        setIs(_is_);

        setDataName(_dataName_);

    }
    public Object clone()
    {
        return new ADateFormatClause(
            (TDate) cloneNode(_date_),
            (TFormat) cloneNode(_format_),
            (TIs) cloneNode(_is_),
            (TDataName) cloneNode(_dataName_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADateFormatClause(this);
    }

    public TDate getDate()
    {
        return _date_;
    }

    public void setDate(TDate node)
    {
        if(_date_ != null)
        {
            _date_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _date_ = node;
    }

    public TFormat getFormat()
    {
        return _format_;
    }

    public void setFormat(TFormat node)
    {
        if(_format_ != null)
        {
            _format_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _format_ = node;
    }

    public TIs getIs()
    {
        return _is_;
    }

    public void setIs(TIs node)
    {
        if(_is_ != null)
        {
            _is_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _is_ = node;
    }

    public TDataName getDataName()
    {
        return _dataName_;
    }

    public void setDataName(TDataName node)
    {
        if(_dataName_ != null)
        {
            _dataName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dataName_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_date_)
            + toString(_format_)
            + toString(_is_)
            + toString(_dataName_);
    }

    void removeChild(Node child)
    {
        if(_date_ == child)
        {
            _date_ = null;
            return;
        }

        if(_format_ == child)
        {
            _format_ = null;
            return;
        }

        if(_is_ == child)
        {
            _is_ = null;
            return;
        }

        if(_dataName_ == child)
        {
            _dataName_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_date_ == oldChild)
        {
            setDate((TDate) newChild);
            return;
        }

        if(_format_ == oldChild)
        {
            setFormat((TFormat) newChild);
            return;
        }

        if(_is_ == oldChild)
        {
            setIs((TIs) newChild);
            return;
        }

        if(_dataName_ == oldChild)
        {
            setDataName((TDataName) newChild);
            return;
        }

    }
}
