/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class ADescendingAscendingOrDescending extends PAscendingOrDescending
{
    private TDescending _descending_;

    public ADescendingAscendingOrDescending()
    {
    }

    public ADescendingAscendingOrDescending(
        TDescending _descending_)
    {
        setDescending(_descending_);

    }
    public Object clone()
    {
        return new ADescendingAscendingOrDescending(
            (TDescending) cloneNode(_descending_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADescendingAscendingOrDescending(this);
    }

    public TDescending getDescending()
    {
        return _descending_;
    }

    public void setDescending(TDescending node)
    {
        if(_descending_ != null)
        {
            _descending_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _descending_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_descending_);
    }

    void removeChild(Node child)
    {
        if(_descending_ == child)
        {
            _descending_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_descending_ == oldChild)
        {
            setDescending((TDescending) newChild);
            return;
        }

    }
}
