/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class ADisplay1UsagePhrase extends PUsagePhrase
{
    private TDisplay1 _display1_;
    private TNative _native_;

    public ADisplay1UsagePhrase()
    {
    }

    public ADisplay1UsagePhrase(
        TDisplay1 _display1_,
        TNative _native_)
    {
        setDisplay1(_display1_);

        setNative(_native_);

    }
    public Object clone()
    {
        return new ADisplay1UsagePhrase(
            (TDisplay1) cloneNode(_display1_),
            (TNative) cloneNode(_native_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADisplay1UsagePhrase(this);
    }

    public TDisplay1 getDisplay1()
    {
        return _display1_;
    }

    public void setDisplay1(TDisplay1 node)
    {
        if(_display1_ != null)
        {
            _display1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _display1_ = node;
    }

    public TNative getNative()
    {
        return _native_;
    }

    public void setNative(TNative node)
    {
        if(_native_ != null)
        {
            _native_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _native_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_display1_)
            + toString(_native_);
    }

    void removeChild(Node child)
    {
        if(_display1_ == child)
        {
            _display1_ = null;
            return;
        }

        if(_native_ == child)
        {
            _native_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_display1_ == oldChild)
        {
            setDisplay1((TDisplay1) newChild);
            return;
        }

        if(_native_ == oldChild)
        {
            setNative((TNative) newChild);
            return;
        }

    }
}
