/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import net.sf.cb2xml.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ADisplay1UsagePhrase extends PUsagePhrase
{
    private TDisplay1 _display1_;
    private TNative _native_;

    public ADisplay1UsagePhrase()
    {
        // Constructor
    }

    public ADisplay1UsagePhrase(
        @SuppressWarnings("hiding") TDisplay1 _display1_,
        @SuppressWarnings("hiding") TNative _native_)
    {
        // Constructor
        setDisplay1(_display1_);

        setNative(_native_);

    }

    @Override
    public Object clone()
    {
        return new ADisplay1UsagePhrase(
            cloneNode(this._display1_),
            cloneNode(this._native_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADisplay1UsagePhrase(this);
    }

    public TDisplay1 getDisplay1()
    {
        return this._display1_;
    }

    public void setDisplay1(TDisplay1 node)
    {
        if(this._display1_ != null)
        {
            this._display1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._display1_ = node;
    }

    public TNative getNative()
    {
        return this._native_;
    }

    public void setNative(TNative node)
    {
        if(this._native_ != null)
        {
            this._native_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._native_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._display1_)
            + toString(this._native_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._display1_ == child)
        {
            this._display1_ = null;
            return;
        }

        if(this._native_ == child)
        {
            this._native_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._display1_ == oldChild)
        {
            setDisplay1((TDisplay1) newChild);
            return;
        }

        if(this._native_ == oldChild)
        {
            setNative((TNative) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
