/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class ADollarCharacterSubstring extends PCharacterSubstring
{
    private TDollar _dollar_;

    public ADollarCharacterSubstring()
    {
    }

    public ADollarCharacterSubstring(
        TDollar _dollar_)
    {
        setDollar(_dollar_);

    }
    public Object clone()
    {
        return new ADollarCharacterSubstring(
            (TDollar) cloneNode(_dollar_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADollarCharacterSubstring(this);
    }

    public TDollar getDollar()
    {
        return _dollar_;
    }

    public void setDollar(TDollar node)
    {
        if(_dollar_ != null)
        {
            _dollar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dollar_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_dollar_);
    }

    void removeChild(Node child)
    {
        if(_dollar_ == child)
        {
            _dollar_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_dollar_ == oldChild)
        {
            setDollar((TDollar) newChild);
            return;
        }

    }
}
