/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class ADotZeeCharacterSubstring extends PCharacterSubstring
{
    private TDotZee _dotZee_;

    public ADotZeeCharacterSubstring()
    {
    }

    public ADotZeeCharacterSubstring(
        TDotZee _dotZee_)
    {
        setDotZee(_dotZee_);

    }
    public Object clone()
    {
        return new ADotZeeCharacterSubstring(
            (TDotZee) cloneNode(_dotZee_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADotZeeCharacterSubstring(this);
    }

    public TDotZee getDotZee()
    {
        return _dotZee_;
    }

    public void setDotZee(TDotZee node)
    {
        if(_dotZee_ != null)
        {
            _dotZee_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dotZee_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_dotZee_);
    }

    void removeChild(Node child)
    {
        if(_dotZee_ == child)
        {
            _dotZee_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_dotZee_ == oldChild)
        {
            setDotZee((TDotZee) newChild);
            return;
        }

    }
}
