/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import net.sf.cb2xml.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ADotZeeCharacterSubstring extends PCharacterSubstring
{
    private TDotZee _dotZee_;

    public ADotZeeCharacterSubstring()
    {
        // Constructor
    }

    public ADotZeeCharacterSubstring(
        @SuppressWarnings("hiding") TDotZee _dotZee_)
    {
        // Constructor
        setDotZee(_dotZee_);

    }

    @Override
    public Object clone()
    {
        return new ADotZeeCharacterSubstring(
            cloneNode(this._dotZee_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADotZeeCharacterSubstring(this);
    }

    public TDotZee getDotZee()
    {
        return this._dotZee_;
    }

    public void setDotZee(TDotZee node)
    {
        if(this._dotZee_ != null)
        {
            this._dotZee_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dotZee_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dotZee_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dotZee_ == child)
        {
            this._dotZee_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dotZee_ == oldChild)
        {
            setDotZee((TDotZee) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
