/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class ADotPlusCharacterSubstring extends PCharacterSubstring
{
    private TDotPlus _dotPlus_;

    public ADotPlusCharacterSubstring()
    {
    }

    public ADotPlusCharacterSubstring(
        TDotPlus _dotPlus_)
    {
        setDotPlus(_dotPlus_);

    }
    public Object clone()
    {
        return new ADotPlusCharacterSubstring(
            (TDotPlus) cloneNode(_dotPlus_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADotPlusCharacterSubstring(this);
    }

    public TDotPlus getDotPlus()
    {
        return _dotPlus_;
    }

    public void setDotPlus(TDotPlus node)
    {
        if(_dotPlus_ != null)
        {
            _dotPlus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dotPlus_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_dotPlus_);
    }

    void removeChild(Node child)
    {
        if(_dotPlus_ == child)
        {
            _dotPlus_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_dotPlus_ == oldChild)
        {
            setDotPlus((TDotPlus) newChild);
            return;
        }

    }
}
