/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class AExternalClauseClause extends PClause
{
    private PExternalClause _externalClause_;

    public AExternalClauseClause()
    {
    }

    public AExternalClauseClause(
        PExternalClause _externalClause_)
    {
        setExternalClause(_externalClause_);

    }
    public Object clone()
    {
        return new AExternalClauseClause(
            (PExternalClause) cloneNode(_externalClause_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExternalClauseClause(this);
    }

    public PExternalClause getExternalClause()
    {
        return _externalClause_;
    }

    public void setExternalClause(PExternalClause node)
    {
        if(_externalClause_ != null)
        {
            _externalClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _externalClause_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_externalClause_);
    }

    void removeChild(Node child)
    {
        if(_externalClause_ == child)
        {
            _externalClause_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_externalClause_ == oldChild)
        {
            setExternalClause((PExternalClause) newChild);
            return;
        }

    }
}
