/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class AHighValuesLiteral extends PLiteral
{
    private THighValues _highValues_;

    public AHighValuesLiteral()
    {
    }

    public AHighValuesLiteral(
        THighValues _highValues_)
    {
        setHighValues(_highValues_);

    }
    public Object clone()
    {
        return new AHighValuesLiteral(
            (THighValues) cloneNode(_highValues_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHighValuesLiteral(this);
    }

    public THighValues getHighValues()
    {
        return _highValues_;
    }

    public void setHighValues(THighValues node)
    {
        if(_highValues_ != null)
        {
            _highValues_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _highValues_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_highValues_);
    }

    void removeChild(Node child)
    {
        if(_highValues_ == child)
        {
            _highValues_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_highValues_ == oldChild)
        {
            setHighValues((THighValues) newChild);
            return;
        }

    }
}
