/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class AIndexUsagePhrase extends PUsagePhrase
{
    private TIndex _index_;

    public AIndexUsagePhrase()
    {
    }

    public AIndexUsagePhrase(
        TIndex _index_)
    {
        setIndex(_index_);

    }
    public Object clone()
    {
        return new AIndexUsagePhrase(
            (TIndex) cloneNode(_index_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIndexUsagePhrase(this);
    }

    public TIndex getIndex()
    {
        return _index_;
    }

    public void setIndex(TIndex node)
    {
        if(_index_ != null)
        {
            _index_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _index_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_index_);
    }

    void removeChild(Node child)
    {
        if(_index_ == child)
        {
            _index_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_index_ == oldChild)
        {
            setIndex((TIndex) newChild);
            return;
        }

    }
}
