/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class AJustifiedClauseClause extends PClause
{
    private PJustifiedClause _justifiedClause_;

    public AJustifiedClauseClause()
    {
    }

    public AJustifiedClauseClause(
        PJustifiedClause _justifiedClause_)
    {
        setJustifiedClause(_justifiedClause_);

    }
    public Object clone()
    {
        return new AJustifiedClauseClause(
            (PJustifiedClause) cloneNode(_justifiedClause_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAJustifiedClauseClause(this);
    }

    public PJustifiedClause getJustifiedClause()
    {
        return _justifiedClause_;
    }

    public void setJustifiedClause(PJustifiedClause node)
    {
        if(_justifiedClause_ != null)
        {
            _justifiedClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _justifiedClause_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_justifiedClause_);
    }

    void removeChild(Node child)
    {
        if(_justifiedClause_ == child)
        {
            _justifiedClause_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_justifiedClause_ == oldChild)
        {
            setJustifiedClause((PJustifiedClause) newChild);
            return;
        }

    }
}
