/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class ALeadingLeadingOrTrailing extends PLeadingOrTrailing
{
    private TLeading _leading_;

    public ALeadingLeadingOrTrailing()
    {
    }

    public ALeadingLeadingOrTrailing(
        TLeading _leading_)
    {
        setLeading(_leading_);

    }
    public Object clone()
    {
        return new ALeadingLeadingOrTrailing(
            (TLeading) cloneNode(_leading_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALeadingLeadingOrTrailing(this);
    }

    public TLeading getLeading()
    {
        return _leading_;
    }

    public void setLeading(TLeading node)
    {
        if(_leading_ != null)
        {
            _leading_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _leading_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_leading_);
    }

    void removeChild(Node child)
    {
        if(_leading_ == child)
        {
            _leading_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_leading_ == oldChild)
        {
            setLeading((TLeading) newChild);
            return;
        }

    }
}
