/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class ANumber88Number extends PNumber
{
    private TNumber88 _number88_;

    public ANumber88Number()
    {
    }

    public ANumber88Number(
        TNumber88 _number88_)
    {
        setNumber88(_number88_);

    }
    public Object clone()
    {
        return new ANumber88Number(
            (TNumber88) cloneNode(_number88_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumber88Number(this);
    }

    public TNumber88 getNumber88()
    {
        return _number88_;
    }

    public void setNumber88(TNumber88 node)
    {
        if(_number88_ != null)
        {
            _number88_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _number88_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_number88_);
    }

    void removeChild(Node child)
    {
        if(_number88_ == child)
        {
            _number88_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_number88_ == oldChild)
        {
            setNumber88((TNumber88) newChild);
            return;
        }

    }
}
