/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class AOccursClauseClause extends PClause
{
    private POccursClause _occursClause_;

    public AOccursClauseClause()
    {
    }

    public AOccursClauseClause(
        POccursClause _occursClause_)
    {
        setOccursClause(_occursClause_);

    }
    public Object clone()
    {
        return new AOccursClauseClause(
            (POccursClause) cloneNode(_occursClause_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOccursClauseClause(this);
    }

    public POccursClause getOccursClause()
    {
        return _occursClause_;
    }

    public void setOccursClause(POccursClause node)
    {
        if(_occursClause_ != null)
        {
            _occursClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _occursClause_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_occursClause_);
    }

    void removeChild(Node child)
    {
        if(_occursClause_ == child)
        {
            _occursClause_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_occursClause_ == oldChild)
        {
            setOccursClause((POccursClause) newChild);
            return;
        }

    }
}
