/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class APackedDecimalUsagePhrase extends PUsagePhrase
{
    private TPackedDecimal _packedDecimal_;

    public APackedDecimalUsagePhrase()
    {
    }

    public APackedDecimalUsagePhrase(
        TPackedDecimal _packedDecimal_)
    {
        setPackedDecimal(_packedDecimal_);

    }
    public Object clone()
    {
        return new APackedDecimalUsagePhrase(
            (TPackedDecimal) cloneNode(_packedDecimal_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPackedDecimalUsagePhrase(this);
    }

    public TPackedDecimal getPackedDecimal()
    {
        return _packedDecimal_;
    }

    public void setPackedDecimal(TPackedDecimal node)
    {
        if(_packedDecimal_ != null)
        {
            _packedDecimal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _packedDecimal_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_packedDecimal_);
    }

    void removeChild(Node child)
    {
        if(_packedDecimal_ == child)
        {
            _packedDecimal_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_packedDecimal_ == oldChild)
        {
            setPackedDecimal((TPackedDecimal) newChild);
            return;
        }

    }
}
