/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class APointerUsagePhrase extends PUsagePhrase
{
    private TPointer _pointer_;

    public APointerUsagePhrase()
    {
    }

    public APointerUsagePhrase(
        TPointer _pointer_)
    {
        setPointer(_pointer_);

    }
    public Object clone()
    {
        return new APointerUsagePhrase(
            (TPointer) cloneNode(_pointer_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPointerUsagePhrase(this);
    }

    public TPointer getPointer()
    {
        return _pointer_;
    }

    public void setPointer(TPointer node)
    {
        if(_pointer_ != null)
        {
            _pointer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _pointer_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_pointer_);
    }

    void removeChild(Node child)
    {
        if(_pointer_ == child)
        {
            _pointer_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_pointer_ == oldChild)
        {
            setPointer((TPointer) newChild);
            return;
        }

    }
}
