/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class AProcedurePointerUsagePhrase extends PUsagePhrase
{
    private TProcedurePointer _procedurePointer_;

    public AProcedurePointerUsagePhrase()
    {
    }

    public AProcedurePointerUsagePhrase(
        TProcedurePointer _procedurePointer_)
    {
        setProcedurePointer(_procedurePointer_);

    }
    public Object clone()
    {
        return new AProcedurePointerUsagePhrase(
            (TProcedurePointer) cloneNode(_procedurePointer_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProcedurePointerUsagePhrase(this);
    }

    public TProcedurePointer getProcedurePointer()
    {
        return _procedurePointer_;
    }

    public void setProcedurePointer(TProcedurePointer node)
    {
        if(_procedurePointer_ != null)
        {
            _procedurePointer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _procedurePointer_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_procedurePointer_);
    }

    void removeChild(Node child)
    {
        if(_procedurePointer_ == child)
        {
            _procedurePointer_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_procedurePointer_ == oldChild)
        {
            setProcedurePointer((TProcedurePointer) newChild);
            return;
        }

    }
}
