/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class AQuotesLiteral extends PLiteral
{
    private TQuotes _quotes_;

    public AQuotesLiteral()
    {
    }

    public AQuotesLiteral(
        TQuotes _quotes_)
    {
        setQuotes(_quotes_);

    }
    public Object clone()
    {
        return new AQuotesLiteral(
            (TQuotes) cloneNode(_quotes_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAQuotesLiteral(this);
    }

    public TQuotes getQuotes()
    {
        return _quotes_;
    }

    public void setQuotes(TQuotes node)
    {
        if(_quotes_ != null)
        {
            _quotes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _quotes_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_quotes_);
    }

    void removeChild(Node child)
    {
        if(_quotes_ == child)
        {
            _quotes_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_quotes_ == oldChild)
        {
            setQuotes((TQuotes) newChild);
            return;
        }

    }
}
