/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class ARedefinesClause extends PRedefinesClause
{
    private TRedefines _redefines_;
    private TDataName _dataName_;

    public ARedefinesClause()
    {
    }

    public ARedefinesClause(
        TRedefines _redefines_,
        TDataName _dataName_)
    {
        setRedefines(_redefines_);

        setDataName(_dataName_);

    }
    public Object clone()
    {
        return new ARedefinesClause(
            (TRedefines) cloneNode(_redefines_),
            (TDataName) cloneNode(_dataName_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARedefinesClause(this);
    }

    public TRedefines getRedefines()
    {
        return _redefines_;
    }

    public void setRedefines(TRedefines node)
    {
        if(_redefines_ != null)
        {
            _redefines_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _redefines_ = node;
    }

    public TDataName getDataName()
    {
        return _dataName_;
    }

    public void setDataName(TDataName node)
    {
        if(_dataName_ != null)
        {
            _dataName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dataName_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_redefines_)
            + toString(_dataName_);
    }

    void removeChild(Node child)
    {
        if(_redefines_ == child)
        {
            _redefines_ = null;
            return;
        }

        if(_dataName_ == child)
        {
            _dataName_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_redefines_ == oldChild)
        {
            setRedefines((TRedefines) newChild);
            return;
        }

        if(_dataName_ == oldChild)
        {
            setDataName((TDataName) newChild);
            return;
        }

    }
}
