/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import net.sf.cb2xml.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ARightLeftOrRight extends PLeftOrRight
{
    private TRight _right_;

    public ARightLeftOrRight()
    {
        // Constructor
    }

    public ARightLeftOrRight(
        @SuppressWarnings("hiding") TRight _right_)
    {
        // Constructor
        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new ARightLeftOrRight(
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARightLeftOrRight(this);
    }

    public TRight getRight()
    {
        return this._right_;
    }

    public void setRight(TRight node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._right_ == oldChild)
        {
            setRight((TRight) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
