/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class ASequenceGroupItem extends PGroupItem
{
    private PGroupItem _groupItem_;
    private TDot _dot_;
    private PElementaryItem _elementaryItem_;

    public ASequenceGroupItem()
    {
    }

    public ASequenceGroupItem(
        PGroupItem _groupItem_,
        TDot _dot_,
        PElementaryItem _elementaryItem_)
    {
        setGroupItem(_groupItem_);

        setDot(_dot_);

        setElementaryItem(_elementaryItem_);

    }
    public Object clone()
    {
        return new ASequenceGroupItem(
            (PGroupItem) cloneNode(_groupItem_),
            (TDot) cloneNode(_dot_),
            (PElementaryItem) cloneNode(_elementaryItem_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASequenceGroupItem(this);
    }

    public PGroupItem getGroupItem()
    {
        return _groupItem_;
    }

    public void setGroupItem(PGroupItem node)
    {
        if(_groupItem_ != null)
        {
            _groupItem_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _groupItem_ = node;
    }

    public TDot getDot()
    {
        return _dot_;
    }

    public void setDot(TDot node)
    {
        if(_dot_ != null)
        {
            _dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _dot_ = node;
    }

    public PElementaryItem getElementaryItem()
    {
        return _elementaryItem_;
    }

    public void setElementaryItem(PElementaryItem node)
    {
        if(_elementaryItem_ != null)
        {
            _elementaryItem_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _elementaryItem_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_groupItem_)
            + toString(_dot_)
            + toString(_elementaryItem_);
    }

    void removeChild(Node child)
    {
        if(_groupItem_ == child)
        {
            _groupItem_ = null;
            return;
        }

        if(_dot_ == child)
        {
            _dot_ = null;
            return;
        }

        if(_elementaryItem_ == child)
        {
            _elementaryItem_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_groupItem_ == oldChild)
        {
            setGroupItem((PGroupItem) newChild);
            return;
        }

        if(_dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

        if(_elementaryItem_ == oldChild)
        {
            setElementaryItem((PElementaryItem) newChild);
            return;
        }

    }
}
