/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class AValueClause extends PValueClause
{
    private TValue _value_;
    private TIs _is_;
    private TAll _all_;
    private PLiteral _literal_;

    public AValueClause()
    {
    }

    public AValueClause(
        TValue _value_,
        TIs _is_,
        TAll _all_,
        PLiteral _literal_)
    {
        setValue(_value_);

        setIs(_is_);

        setAll(_all_);

        setLiteral(_literal_);

    }
    public Object clone()
    {
        return new AValueClause(
            (TValue) cloneNode(_value_),
            (TIs) cloneNode(_is_),
            (TAll) cloneNode(_all_),
            (PLiteral) cloneNode(_literal_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAValueClause(this);
    }

    public TValue getValue()
    {
        return _value_;
    }

    public void setValue(TValue node)
    {
        if(_value_ != null)
        {
            _value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _value_ = node;
    }

    public TIs getIs()
    {
        return _is_;
    }

    public void setIs(TIs node)
    {
        if(_is_ != null)
        {
            _is_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _is_ = node;
    }

    public TAll getAll()
    {
        return _all_;
    }

    public void setAll(TAll node)
    {
        if(_all_ != null)
        {
            _all_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _all_ = node;
    }

    public PLiteral getLiteral()
    {
        return _literal_;
    }

    public void setLiteral(PLiteral node)
    {
        if(_literal_ != null)
        {
            _literal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _literal_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_value_)
            + toString(_is_)
            + toString(_all_)
            + toString(_literal_);
    }

    void removeChild(Node child)
    {
        if(_value_ == child)
        {
            _value_ = null;
            return;
        }

        if(_is_ == child)
        {
            _is_ = null;
            return;
        }

        if(_all_ == child)
        {
            _all_ = null;
            return;
        }

        if(_literal_ == child)
        {
            _literal_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_value_ == oldChild)
        {
            setValue((TValue) newChild);
            return;
        }

        if(_is_ == oldChild)
        {
            setIs((TIs) newChild);
            return;
        }

        if(_all_ == oldChild)
        {
            setAll((TAll) newChild);
            return;
        }

        if(_literal_ == oldChild)
        {
            setLiteral((PLiteral) newChild);
            return;
        }

    }
}
