/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import java.util.*;
import net.sf.cb2xml.sablecc.analysis.*;

public final class AValueItemElementaryItem extends PElementaryItem
{
    private PValueItem _valueItem_;

    public AValueItemElementaryItem()
    {
    }

    public AValueItemElementaryItem(
        PValueItem _valueItem_)
    {
        setValueItem(_valueItem_);

    }
    public Object clone()
    {
        return new AValueItemElementaryItem(
            (PValueItem) cloneNode(_valueItem_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAValueItemElementaryItem(this);
    }

    public PValueItem getValueItem()
    {
        return _valueItem_;
    }

    public void setValueItem(PValueItem node)
    {
        if(_valueItem_ != null)
        {
            _valueItem_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _valueItem_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_valueItem_);
    }

    void removeChild(Node child)
    {
        if(_valueItem_ == child)
        {
            _valueItem_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_valueItem_ == oldChild)
        {
            setValueItem((PValueItem) newChild);
            return;
        }

    }
}
