/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.node;

import net.sf.cb2xml.sablecc.analysis.*;

public final class X1TDataName extends XTDataName
{
    private XTDataName _xTDataName_;
    private TDataName _tDataName_;

    public X1TDataName()
    {
    }

    public X1TDataName(
        XTDataName _xTDataName_,
        TDataName _tDataName_)
    {
        setXTDataName(_xTDataName_);
        setTDataName(_tDataName_);
    }

    public Object clone()
    {
        throw new RuntimeException("Unsupported Operation");
    }

    public void apply(Switch sw)
    {
        throw new RuntimeException("Switch not supported.");
    }

    public XTDataName getXTDataName()
    {
        return _xTDataName_;
    }

    public void setXTDataName(XTDataName node)
    {
        if(_xTDataName_ != null)
        {
            _xTDataName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _xTDataName_ = node;
    }

    public TDataName getTDataName()
    {
        return _tDataName_;
    }

    public void setTDataName(TDataName node)
    {
        if(_tDataName_ != null)
        {
            _tDataName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _tDataName_ = node;
    }

    void removeChild(Node child)
    {
        if(_xTDataName_ == child)
        {
            _xTDataName_ = null;
        }

        if(_tDataName_ == child)
        {
            _tDataName_ = null;
        }
    }

    void replaceChild(Node oldChild, Node newChild)
    {
    }

    public String toString()
    {
        return "" +
            toString(_xTDataName_) +
            toString(_tDataName_);
    }
}
