/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.cb2xml.sablecc.lexer;

public class LexerException extends Exception
{
    public LexerException(String message)
    {
        super(message);
    }
}
